[package]
name = "compiler-rs-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
# miniserde = "0.1.43"
serde-wasm-bindgen = "0.6.5"
wasm-bindgen = "0.2.106"
serde = { version = "1.0", features = ["derive"] }

[lib]
crate-type = ["cdylib"]
